/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hongzhen_com_jnitypeturn_JNITypeTurnUtils */

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hongzhen_com_jnitypeturn_JNITypeTurnUtils
 * Method:    getTest
 * Signature: (Lhongzhen/com/jnitypeturn/TestBean;)V
 */
JNIEXPORT void JNICALL Java_hongzhen_com_jnitypeturn_JNITypeTurnUtils_getTest
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif

